config/routes.rb
AccesoTotal::Application.routes.draw do
  resources :mail_users

  resources :participations

  resources :questions

  resources :bottles

  resources :invites

  resources :roles

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}

  devise_scope :user do
	  get 'logout', :to => "devise/sessions#destroy"
	  get 'signin', :to => "devise/sessions#new"
	  get 'signup', :to => "devise/registrations#new"
  end

  resources :users do
    match 'get_participations'
  end

  match 'valida_edad' => "display#valida_edad", :as => :valida_edad
  match 'elige_pregunta' => "display#elige_pregunta", :as => :elige_pregunta 
  match 'registra_participacion' => "display#registra_participacion", :as => :registra_participacion 
  match 'registra_codigo' => "display#registra_codigo", :as => :registra_codigo 
  match 'tab' => "display#tab", :as => :tab
  match 'invita_email' => "display#invita_email", :as => :invita_email

  match 'find_or_create_user' => "users#find_or_create_user", :as => :find_or_create_user
  match 'validate_bottle' => "bottles#validate_bottle", :as => :validate_bottle

  match 'admin' => 'admin#index', :as => :admin

  match 'admin/logout', :to => "admin#logout", :as => :admin_logout
  
  match 'mail_users' => "mail_user", :as => :mail_users

  root :to => 'display#index'

end

app/models/invite.rb
class Invite < ActiveRecord::Base
  attr_accessible :invited_uid, :user_id

  belongs_to :user
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  
  load_and_authorize_resource

  # GET /invites
  # GET /invites.json
  def index
    @invites = Invite.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @invites }
    end
  end

  # GET /invites/1
  # GET /invites/1.json
  def show
    @invite = Invite.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @invite }
    end
  end

  # GET /invites/new
  # GET /invites/new.json
  def new
    @invite = Invite.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @invite }
    end
  end

  # GET /invites/1/edit
  def edit
    @invite = Invite.find(params[:id])
  end

  # POST /invites
  # POST /invites.json
  def create
    @invite = Invite.new(params[:invite])

    respond_to do |format|
      if @invite.save
        format.html { redirect_to @invite, notice: 'Invite was successfully created.' }
        format.json { render json: @invite, status: :created, location: @invite }
      else
        format.html { render action: "new" }
        format.json { render json: @invite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /invites/1
  # PUT /invites/1.json
  def update
    @invite = Invite.find(params[:id])

    respond_to do |format|
      if @invite.update_attributes(params[:invite])
        format.html { redirect_to @invite, notice: 'Invite was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @invite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invites/1
  # DELETE /invites/1.json
  def destroy
    @invite = Invite.find(params[:id])
    @invite.destroy

    respond_to do |format|
      format.html { redirect_to invites_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/views/invites/_form.html.erb
<%= form_for(@invite) do |f| %>
  <% if @invite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invite.errors.count, "error") %> prohibited this invite from being saved:</h2>

      <ul>
      <% @invite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :invited_uid %><br />
    <%= f.text_field :invited_uid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invites/edit.html.erb
<h1>Editing invite</h1>

<%= render 'form' %>

<%= link_to 'Show', @invite %> |
<%= link_to 'Back', invites_path %>

app/views/invites/index.html.erb
<h1>Listing invites</h1>

<table>
  <tr>
    <th>User</th>
    <th>Invited uid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @invites.each do |invite| %>
  <tr>
    <td><%= invite.user_id %></td>
    <td><%= invite.invited_uid %></td>
    <td><%= link_to 'Show', invite %></td>
    <td><%= link_to 'Edit', edit_invite_path(invite) %></td>
    <td><%= link_to 'Destroy', invite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Invite', new_invite_path %>

app/views/invites/new.html.erb
<h1>New invite</h1>

<%= render 'form' %>

<%= link_to 'Back', invites_path %>

app/views/invites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @invite.user_id %>
</p>

<p>
  <b>Invited uid:</b>
  <%= @invite.invited_uid %>
</p>


<%= link_to 'Edit', edit_invite_path(@invite) %> |
<%= link_to 'Back', invites_path %>