config/routes.rb
AccesoTotal::Application.routes.draw do
  resources :mail_users

  resources :participations

  resources :questions

  resources :bottles

  resources :invites

  resources :roles

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}

  devise_scope :user do
	  get 'logout', :to => "devise/sessions#destroy"
	  get 'signin', :to => "devise/sessions#new"
	  get 'signup', :to => "devise/registrations#new"
  end

  resources :users do
    match 'get_participations'
  end

  match 'valida_edad' => "display#valida_edad", :as => :valida_edad
  match 'elige_pregunta' => "display#elige_pregunta", :as => :elige_pregunta 
  match 'registra_participacion' => "display#registra_participacion", :as => :registra_participacion 
  match 'registra_codigo' => "display#registra_codigo", :as => :registra_codigo 
  match 'tab' => "display#tab", :as => :tab
  match 'invita_email' => "display#invita_email", :as => :invita_email

  match 'find_or_create_user' => "users#find_or_create_user", :as => :find_or_create_user
  match 'validate_bottle' => "bottles#validate_bottle", :as => :validate_bottle

  match 'admin' => 'admin#index', :as => :admin

  match 'admin/logout', :to => "admin#logout", :as => :admin_logout
  
  match 'mail_users' => "mail_user", :as => :mail_users

  root :to => 'display#index'

end

app/models/mail_user.rb
class MailUser < ActiveRecord::Base
  attr_accessible :email, :name
end

app/controllers/mail_users_controller.rb
class MailUsersController < ApplicationController
  # GET /mail_users
  # GET /mail_users.json
  def index
    @mail_users = MailUser.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mail_users }
    end
  end

  # GET /mail_users/1
  # GET /mail_users/1.json
  def show
    @mail_user = MailUser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mail_user }
    end
  end

  # GET /mail_users/new
  # GET /mail_users/new.json
  def new
    @mail_user = MailUser.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mail_user }
    end
  end

  # GET /mail_users/1/edit
  def edit
    @mail_user = MailUser.find(params[:id])
  end

  # POST /mail_users
  # POST /mail_users.json
  def create
    @mail_user = MailUser.new(params[:mail_user])
	
    respond_to do |format|
      if @mail_user.save
        format.html { redirect_to @mail_user, notice: 'Mail user was successfully created.' }
        format.json { render json: @mail_user, status: :created, location: @mail_user }
      else
        format.html { render action: "new" }
        format.json { render json: @mail_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mail_users/1
  # PUT /mail_users/1.json
  def update
    @mail_user = MailUser.find(params[:id])

    respond_to do |format|
      if @mail_user.update_attributes(params[:mail_user])
        format.html { redirect_to @mail_user, notice: 'Mail user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mail_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mail_users/1
  # DELETE /mail_users/1.json
  def destroy
    @mail_user = MailUser.find(params[:id])
    @mail_user.destroy

    respond_to do |format|
      format.html { redirect_to mail_users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/mail_users_helper.rb
module MailUsersHelper
end

app/views/mail_users/_form.html.erb
<%= form_for(@mail_user) do |f| %>
  <% if @mail_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mail_user.errors.count, "error") %> prohibited this mail_user from being saved:</h2>

      <ul>
      <% @mail_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mail_users/edit.html.erb
<h1>Editing mail_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @mail_user %> |
<%= link_to 'Back', mail_users_path %>

app/views/mail_users/index.html.erb
<h1>Listing mail_users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mail_users.each do |mail_user| %>
  <tr>
    <td><%= mail_user.name %></td>
    <td><%= mail_user.email %></td>
    <td><%= link_to 'Show', mail_user %></td>
    <td><%= link_to 'Edit', edit_mail_user_path(mail_user) %></td>
    <td><%= link_to 'Destroy', mail_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mail user', new_mail_user_path %>

app/views/mail_users/new.html.erb
<h1>New mail_user</h1>

<%= render 'form' %>

<%= link_to 'Back', mail_users_path %>

app/views/mail_users/respuesta.html.erb
<h1>Tu amigo <%= usuario %> te acaba de invitar a ser parte de Acceso Total: Cannes.</h1>
<p>Aprovecha esta oportunidad y atrévete a vivir una experiencia que el dinero no puede comprar. 
Vive la magia de Cannes, Francia; visita lugares a los que muy pocas personas pueden ingresar 
y vive el glamour y la seducción de una de las ciudades más emblemáticas del mundo.</p>
 
<p>Ingresa al siguiente enlace y descubre cómo ganar: <%= link_to( 'http://accesototaltradicional.com/', 'http://accesototaltradicional.com/') %> </p>

app/views/mail_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @mail_user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @mail_user.email %>
</p>


<%= link_to 'Edit', edit_mail_user_path(@mail_user) %> |
<%= link_to 'Back', mail_users_path %>