config/routes.rb
AccesoTotal::Application.routes.draw do
  resources :mail_users

  resources :participations

  resources :questions

  resources :bottles

  resources :invites

  resources :roles

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}

  devise_scope :user do
	  get 'logout', :to => "devise/sessions#destroy"
	  get 'signin', :to => "devise/sessions#new"
	  get 'signup', :to => "devise/registrations#new"
  end

  resources :users do
    match 'get_participations'
  end

  match 'valida_edad' => "display#valida_edad", :as => :valida_edad
  match 'elige_pregunta' => "display#elige_pregunta", :as => :elige_pregunta 
  match 'registra_participacion' => "display#registra_participacion", :as => :registra_participacion 
  match 'registra_codigo' => "display#registra_codigo", :as => :registra_codigo 
  match 'tab' => "display#tab", :as => :tab
  match 'invita_email' => "display#invita_email", :as => :invita_email

  match 'find_or_create_user' => "users#find_or_create_user", :as => :find_or_create_user
  match 'validate_bottle' => "bottles#validate_bottle", :as => :validate_bottle

  match 'admin' => 'admin#index', :as => :admin

  match 'admin/logout', :to => "admin#logout", :as => :admin_logout
  
  match 'mail_users' => "mail_user", :as => :mail_users

  root :to => 'display#index'

end

app/models/bottle.rb
class Bottle < ActiveRecord::Base
  attr_accessible :code

  has_one :participation

  def self.validate_code code
    if b = Bottle.find_by_code(code)
      if Participation.find_by_bottle_id(b.id)
        return nil 
      else
        return b
      end
    else
      return nil 
    end
  end

end

app/controllers/bottles_controller.rb
class BottlesController < ApplicationController

  load_and_authorize_resource

  # GET /bottles
  # GET /bottles.json
  def index
    @bottles = Bottle.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bottles }
    end
  end

  # GET /bottles/1
  # GET /bottles/1.json
  def show
    @bottle = Bottle.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bottle }
    end
  end

  # GET /bottles/new
  # GET /bottles/new.json
  def new
    @bottle = Bottle.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bottle }
    end
  end

  # GET /bottles/1/edit
  def edit
    @bottle = Bottle.find(params[:id])
  end

  # POST /bottles
  # POST /bottles.json
  def create
    @bottle = Bottle.new(params[:bottle])

    respond_to do |format|
      if @bottle.save
        format.html { redirect_to @bottle, notice: 'Bottle was successfully created.' }
        format.json { render json: @bottle, status: :created, location: @bottle }
      else
        format.html { render action: "new" }
        format.json { render json: @bottle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bottles/1
  # PUT /bottles/1.json
  def update
    @bottle = Bottle.find(params[:id])

    respond_to do |format|
      if @bottle.update_attributes(params[:bottle])
        format.html { redirect_to @bottle, notice: 'Bottle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bottle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bottles/1
  # DELETE /bottles/1.json
  def destroy
    @bottle = Bottle.find(params[:id])
    @bottle.destroy

    respond_to do |format|
      format.html { redirect_to bottles_url }
      format.json { head :no_content }
    end
  end

  def validate_bottle
    @bottle = Bottle.validate_code(params[:code])
    
    respond_to do |format|
      format.json { render json: @bottle }
    end

  end
end

app/helpers/bottles_helper.rb
module BottlesHelper
end

app/views/bottles/_form.html.erb
<%= form_for(@bottle) do |f| %>
  <% if @bottle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bottle.errors.count, "error") %> prohibited this bottle from being saved:</h2>

      <ul>
      <% @bottle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bottles/edit.html.erb
<h1>Editing bottle</h1>

<%= render 'form' %>

<%= link_to 'Show', @bottle %> |
<%= link_to 'Back', bottles_path %>

app/views/bottles/index.html.erb
<h1>Listing bottles</h1>

<table>
  <tr>
    <th>Code</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bottles.each do |bottle| %>
  <tr>
    <td><%= bottle.code %></td>
    <td><%= link_to 'Show', bottle %></td>
    <td><%= link_to 'Edit', edit_bottle_path(bottle) %></td>
    <td><%= link_to 'Destroy', bottle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bottle', new_bottle_path %>

app/views/bottles/new.html.erb
<h1>New bottle</h1>

<%= render 'form' %>

<%= link_to 'Back', bottles_path %>

app/views/bottles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @bottle.code %>
</p>


<%= link_to 'Edit', edit_bottle_path(@bottle) %> |
<%= link_to 'Back', bottles_path %>